# Generated by Django 5.2.6 on 2025-09-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_content_alter_post_slug_alter_post_status'),
        ('posts', '0005_post_content_alter_post_slug'),
    ]

    operations = [
    ]
