# Generated by Django 5.2.6 on 2025-09-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_merge_20250907_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
